"""Governance-by-test for the `sim/speculative/` segregation policy.

Mirrors this repo's existing governance-by-test pattern (e.g.
`tools/validate_multi_dataset_real_execution_matrix.py`): the segregation
between the speculative theoretical-exploration track and the real-EEG
dataset-report pipeline (`sciencer_d/btc_icft/`) is enforced by a static
import-graph check, not just a naming convention or docstring promise.
"""
from __future__ import annotations

import ast
from pathlib import Path

import pytest

from sim.speculative import (
    BANNED_REPORT_PHRASES,
    SPECULATIVE_BANNER,
    validate_speculative_text,
)

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SPECULATIVE_DIR = _REPO_ROOT / "sim" / "speculative"
_BTC_ICFT_DIR = _REPO_ROOT / "sciencer_d" / "btc_icft"


def _imported_module_names(py_file: Path) -> list[str]:
    tree = ast.parse(py_file.read_text(encoding="utf-8"))
    names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            names.extend(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            names.append(node.module)
    return names


# ── Import-boundary enforcement ───────────────────────────────────────────────

def test_no_btc_icft_file_imports_sim_speculative():
    """The real-EEG dataset-report pipeline must never depend on the
    speculative track -- a published report's results must never be able
    to trace back to unvalidated theoretical code."""
    offenders = []
    for py_file in _BTC_ICFT_DIR.rglob("*.py"):
        for module in _imported_module_names(py_file):
            if module.startswith("sim.speculative") or module == "sim.speculative":
                offenders.append((str(py_file.relative_to(_REPO_ROOT)), module))
    assert not offenders, f"sciencer_d/btc_icft files import sim.speculative: {offenders}"


def test_no_sim_speculative_file_imports_sciencer_d_btc_icft():
    """The speculative track must never feed on or into the real-EEG
    pipeline's dataset-specific machinery. Importing from `analysis.itct`
    (a separate, already-speculative-adjacent module whose real reusable
    core lives in `analysis.connectivity_topology`) is explicitly permitted
    by the project plan and is not part of this boundary."""
    offenders = []
    for py_file in _SPECULATIVE_DIR.rglob("*.py"):
        for module in _imported_module_names(py_file):
            if module.startswith("sciencer_d.btc_icft") or module == "sciencer_d.btc_icft":
                offenders.append((str(py_file.relative_to(_REPO_ROOT)), module))
    assert not offenders, f"sim/speculative files import sciencer_d.btc_icft: {offenders}"


def test_no_published_dataset_report_directory_contains_speculative_output():
    """Published dataset reports (outputs/btc_icft/**/REPORT_*.md) must
    never live alongside or be generated by speculative output."""
    outputs_btc_icft = _REPO_ROOT / "outputs" / "btc_icft"
    if not outputs_btc_icft.exists():
        pytest.skip("outputs/btc_icft not present in this checkout")
    for report in outputs_btc_icft.rglob("REPORT_*.md"):
        text = report.read_text(encoding="utf-8", errors="ignore")
        assert SPECULATIVE_BANNER not in text, f"{report} unexpectedly contains the speculative banner"


# ── Banned-phrase list drift check ────────────────────────────────────────────

def test_banned_phrase_list_matches_canonical_report_guardrails_base_list():
    """`sim/speculative/__init__.py::BANNED_REPORT_PHRASES` is a deliberate,
    documented duplicate (not an import) of
    `sciencer_d/btc_icft/report_guardrails.py::BANNED_REPORT_PHRASES`, to
    keep the speculative track's import graph fully disjoint from
    `sciencer_d.btc_icft` (see the import-boundary tests above). This test
    is the detection mechanism for the manual-sync obligation that
    duplication creates -- if the canonical list changes and this copy
    isn't updated, this test fails loudly instead of the two guardrails
    silently drifting apart (the exact failure mode Phase 2a of this
    project's plan fixed for the 9 in-pipeline copies)."""
    from sciencer_d.btc_icft.report_guardrails import (
        BANNED_REPORT_PHRASES as canonical_phrases,
    )

    assert set(BANNED_REPORT_PHRASES) == set(canonical_phrases)


# ── validate_speculative_text ─────────────────────────────────────────────────

def test_validate_speculative_text_passes_with_banner_and_no_banned_phrase():
    text = f"{SPECULATIVE_BANNER}\n\nSome ordinary descriptive engineering text."
    validate_speculative_text(text)  # must not raise


def test_validate_speculative_text_raises_without_banner():
    with pytest.raises(ValueError, match="(?i)banner"):
        validate_speculative_text("No banner here, just prose.")


def test_validate_speculative_text_raises_on_banned_phrase():
    text = f"{SPECULATIVE_BANNER}\n\nThis run proves consciousness beyond doubt."
    with pytest.raises(ValueError, match="banned phrase"):
        validate_speculative_text(text)


def test_validate_speculative_text_banned_phrase_check_is_case_insensitive():
    text = f"{SPECULATIVE_BANNER}\n\nQ EQUALS SELF, obviously."
    with pytest.raises(ValueError, match="banned phrase"):
        validate_speculative_text(text)


@pytest.mark.parametrize("phrase", list(BANNED_REPORT_PHRASES))
def test_validate_speculative_text_rejects_every_banned_phrase(phrase):
    text = f"{SPECULATIVE_BANNER}\n\nfiller text {phrase} more filler"
    with pytest.raises(ValueError, match="banned phrase"):
        validate_speculative_text(text)


# ── Modules under sim/speculative/ must produce banner-carrying output ───────

def test_langevin_lattice_report_builder_enforces_banner():
    from sim.speculative.langevin_lattice import build_speculative_report, run_langevin_lattice

    result = run_langevin_lattice(N=6, n_steps=3, seed=0)
    report = build_speculative_report(result)
    assert SPECULATIVE_BANNER in report
