"""
Obsidian vault sync for local agent research loop (P23).

Mirrors key ScienceR-Dsim outputs into an Obsidian vault as Markdown notes.
Creates index note, per-dataset notes, and loop state notes.

stdlib only. Never modifies source artifacts; only writes to vault_root.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class ObsidianSyncConfig:
    """Configuration for the Obsidian sync."""
    vault_root: str
    science_outputs_root: str = "outputs/btc_icft"
    loop_outputs_root: str = "outputs/local_agent_loop"
    index_note: str = "ScienceR-Dsim/INDEX.md"
    dataset_folder: str = "ScienceR-Dsim/datasets"
    loop_folder: str = "ScienceR-Dsim/loop"
    matrix_folder: str = "ScienceR-Dsim/matrix"
    tag: str = "sciencer-dsim"


@dataclass
class ObsidianSyncResult:
    """Summary of what the sync wrote."""
    vault_root: str
    notes_written: list = field(default_factory=list)
    notes_skipped: list = field(default_factory=list)
    error: str = ""


def _safe_note_path(vault_root: Path, rel: str) -> Path:
    p = vault_root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    return p


def _read_json_safe(path: Path) -> Optional[dict]:
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return None


def _dataset_status_note(dataset_id: str, outputs_root: Path) -> str:
    lines = [
        f"# {dataset_id} — ScienceR-Dsim Status",
        "",
        "```",
        f"dataset_id: {dataset_id}",
        "```",
        "",
    ]

    gate_path = outputs_root / dataset_id / "real_execution_gate" / "ready_for_real_execution.json"
    if dataset_id.upper() == "DS005620":
        gate_path = outputs_root / "ds005620_real_execution_gate" / "ready_for_real_execution.json"
    gate = _read_json_safe(gate_path)
    if gate:
        lines += [
            "## Real Execution Gate",
            "",
            f"- ready_for_real_execution: `{gate.get('ready_for_real_execution', 'unknown')}`",
            f"- next_action: `{gate.get('next_action', 'unknown')}`",
            f"- peer_review_confirmed_by_human: `{gate.get('peer_review_confirmed_by_human', False)}`",
            "",
        ]

    operator_path = outputs_root / dataset_id / "real_artifact_operator" / "real_artifact_build_plan.json"
    if dataset_id.upper() == "DS005620":
        operator_path = outputs_root / "ds005620_real_artifact_operator" / "real_artifact_build_plan.json"
    plan = _read_json_safe(operator_path)
    if plan:
        lines += [
            "## Artifact Operator",
            "",
            f"- next_action: `{plan.get('next_action', 'unknown')}`",
            f"- planner_version: `{plan.get('planner_version', 'unknown')}`",
            "",
        ]

    lines += ["---", "", f"#sciencer-dsim #{dataset_id.lower()}"]
    return "\n".join(lines)


def _loop_state_note(loop_root: Path) -> str:
    state = _read_json_safe(loop_root / "loop_state.json") or {}
    next_action = _read_json_safe(loop_root / "loop_next_action.json") or {}
    lines = [
        "# Local Agent Loop — State",
        "",
        f"- status: `{state.get('status', 'unknown')}`",
        f"- steps_total: `{state.get('steps_total', 0)}`",
        f"- steps_completed: `{state.get('steps_completed', 0)}`",
        f"- steps_failed: `{state.get('steps_failed', 0)}`",
        f"- next_action: `{next_action.get('next_action', 'unknown')}`",
        "",
        "---",
        "",
        "#sciencer-dsim #local-agent",
    ]
    return "\n".join(lines)


def _matrix_note(matrix_root: Path) -> str:
    matrix = _read_json_safe(matrix_root / "dataset_source_matrix.json") or {}
    next_actions = _read_json_safe(matrix_root / "next_actions.json") or {}
    lines = [
        "# Multi-Dataset Matrix",
        "",
        f"- global_next_action: `{next_actions.get('global_next_action', 'unknown')}`",
        "",
        "## Datasets",
        "",
    ]
    for ds_id, entry in matrix.items():
        lines.append(f"- **{ds_id}**: `{entry.get('real_execution_supported', False)}`")
    lines += ["", "---", "", "#sciencer-dsim #matrix"]
    return "\n".join(lines)


def _index_note(config: ObsidianSyncConfig, datasets: list[str]) -> str:
    lines = [
        "# ScienceR-Dsim — Obsidian Index",
        "",
        "Auto-generated by the local agent research loop (P23).",
        "Do not edit manually — re-sync to update.",
        "",
        "## Datasets",
        "",
    ]
    for ds in datasets:
        lines.append(f"- [[{config.dataset_folder}/{ds}|{ds}]]")
    lines += [
        "",
        "## Loop State",
        "",
        f"- [[{config.loop_folder}/loop_state|Loop State]]",
        "",
        "## Matrix",
        "",
        f"- [[{config.matrix_folder}/matrix|Multi-Dataset Matrix]]",
        "",
        "---",
        "",
        "#sciencer-dsim",
    ]
    return "\n".join(lines)


def sync_obsidian(
    outputs_root: str | Path,
    vault_root: str | Path,
    config: Optional[ObsidianSyncConfig] = None,
    dataset_ids: Optional[list[str]] = None,
) -> ObsidianSyncResult:
    """
    Mirror ScienceR-Dsim outputs into an Obsidian vault.

    Only writes to vault_root. Never modifies source artifacts.
    """
    vault = Path(vault_root)
    outputs = Path(outputs_root)

    if config is None:
        config = ObsidianSyncConfig(vault_root=str(vault))

    result = ObsidianSyncResult(vault_root=str(vault))

    if dataset_ids is None:
        dataset_ids = ["DS005620", "DS002094", "ds001787", "ds003969", "ds003816", "PhysioNet_GABA"]

    for ds_id in dataset_ids:
        note_content = _dataset_status_note(ds_id, outputs)
        note_path = _safe_note_path(vault, f"{config.dataset_folder}/{ds_id}.md")
        note_path.write_text(note_content, encoding="utf-8")
        result.notes_written.append(str(note_path))

    loop_root = Path(config.loop_outputs_root)
    loop_note = _loop_state_note(loop_root)
    loop_path = _safe_note_path(vault, f"{config.loop_folder}/loop_state.md")
    loop_path.write_text(loop_note, encoding="utf-8")
    result.notes_written.append(str(loop_path))

    matrix_root = outputs / "multi_dataset_real_execution"
    matrix_note = _matrix_note(matrix_root)
    matrix_path = _safe_note_path(vault, f"{config.matrix_folder}/matrix.md")
    matrix_path.write_text(matrix_note, encoding="utf-8")
    result.notes_written.append(str(matrix_path))

    index = _index_note(config, dataset_ids)
    index_path = _safe_note_path(vault, config.index_note)
    index_path.write_text(index, encoding="utf-8")
    result.notes_written.append(str(index_path))

    return result
